#!/usr/bin/env python3
"""
Auto-generated ParaView script for 2D RDE visualization
Generated by: 2D RDE Video Generation System
Configuration: Single detonation wave propagating around annular combustor
"""

import sys
import os
sys.path.insert(0, '/usr/lib/python3/dist-packages')

try:
    import paraview.simple as pv
    print("✅ ParaView loaded successfully for 2D RDE visualization")
    
    # Configuration from C++ video generator
    geometry_config = {
        "inner_radius": 0.05,
        "outer_radius": 0.08,
        "chamber_length": 0.15,
        "domain_angle": 360.0
    }
    
    visualization_config = {
        "temperature_range": [300, 3500],
        "pressure_range": [1e5, 3e6],
        "wave_threshold": 2500.0,
        "resolution": [1920, 1080]
    }
    
    def generate_2d_rde_visualization(case_dir):
        """Main visualization function"""
        
        # Load OpenFOAM case
        foam_file = os.path.join(case_dir, "case.foam")
        reader = pv.OpenFOAMReader(FileName=foam_file)
        reader.MeshRegions = ['internalMesh']
        reader.CellArrays = ['p', 'T', 'U']
        
        # Create render view
        render_view = pv.CreateView('RenderView')
        render_view.ViewSize = visualization_config["resolution"]
        render_view.Background = [0.05, 0.05, 0.15]  # Dark background
        
        # Temperature contours for wave tracking
        temp_contour = pv.Contour(Input=reader)
        temp_contour.ContourBy = ['POINTS', 'T']
        temp_values = list(range(300, 3500, 300))  # Every 300K
        temp_contour.Isosurfaces = temp_values
        
        temp_display = pv.Show(temp_contour, render_view)
        temp_lut = pv.GetColorTransferFunction('T')
        temp_lut.ApplyPreset('Rainbow', True)
        temp_lut.RescaleTransferFunction(*visualization_config["temperature_range"])
        
        # Pressure field visualization
        pressure_display = pv.Show(reader, render_view)
        pressure_display.Representation = 'Surface'
        pressure_display.Opacity = 0.7
        
        pressure_lut = pv.GetColorTransferFunction('p')
        pressure_lut.ApplyPreset('Viridis', True)
        pressure_lut.RescaleTransferFunction(*visualization_config["pressure_range"])
        
        # Wave front detection
        wave_clip = pv.Clip(Input=reader)
        wave_clip.ClipType = 'Scalar'
        wave_clip.Scalars = ['POINTS', 'T']
        wave_clip.Value = visualization_config["wave_threshold"]
        
        wave_display = pv.Show(wave_clip, render_view)
        wave_display.DiffuseColor = [1.0, 0.3, 0.1]  # Orange-red
        wave_display.Representation = 'Wireframe'
        wave_display.LineWidth = 3.0
        
        # Educational annotations
        title_text = pv.Text()
        title_text.Text = "2D Rotating Detonation Engine\nWave Propagation Analysis"
        title_display = pv.Show(title_text, render_view)
        title_display.WindowLocation = 'UpperCenter'
        title_display.FontSize = 18
        title_display.Color = [1.0, 1.0, 1.0]
        
        # Set camera for optimal viewing
        camera = render_view.GetActiveCamera()
        camera.SetPosition(0, 0, 0.3)
        camera.SetFocalPoint(0, 0, geometry_config["chamber_length"]/2)
        camera.SetViewUp(0, 1, 0)
        render_view.ResetCamera()
        
        print("🎬 2D RDE ParaView visualization setup complete")
        return render_view
        
    # Demo execution
    if __name__ == "__main__":
        print("🚀 2D RDE ParaView Integration Demo")
        print("Demo ready - ParaView commands available")
        
except ImportError as e:
    print(f"❌ ParaView not available: {e}")
    print("📝 This script demonstrates the ParaView integration structure")
