# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/openfoam-mcp-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/openfoam-mcp-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/openfoam-mcp-server/CMakeFiles /workspaces/openfoam-mcp-server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/openfoam-mcp-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openfoam-mcp-server

# Build rule for target.
openfoam-mcp-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 openfoam-mcp-server
.PHONY : openfoam-mcp-server

# fast build rule for target.
openfoam-mcp-server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/build
.PHONY : openfoam-mcp-server/fast

#=============================================================================
# Target rules for targets named test_cantera_wrapper

# Build rule for target.
test_cantera_wrapper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cantera_wrapper
.PHONY : test_cantera_wrapper

# fast build rule for target.
test_cantera_wrapper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cantera_wrapper.dir/build.make CMakeFiles/test_cantera_wrapper.dir/build
.PHONY : test_cantera_wrapper/fast

#=============================================================================
# Target rules for targets named test_comprehensive_validation

# Build rule for target.
test_comprehensive_validation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_comprehensive_validation
.PHONY : test_comprehensive_validation

# fast build rule for target.
test_comprehensive_validation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_comprehensive_validation.dir/build.make CMakeFiles/test_comprehensive_validation.dir/build
.PHONY : test_comprehensive_validation/fast

#=============================================================================
# Target rules for targets named test_rde_integration

# Build rule for target.
test_rde_integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_rde_integration
.PHONY : test_rde_integration

# fast build rule for target.
test_rde_integration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/build
.PHONY : test_rde_integration/fast

#=============================================================================
# Target rules for targets named test_cellular_detonation_model

# Build rule for target.
test_cellular_detonation_model: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cellular_detonation_model
.PHONY : test_cellular_detonation_model

# fast build rule for target.
test_cellular_detonation_model/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/build
.PHONY : test_cellular_detonation_model/fast

#=============================================================================
# Target rules for targets named test_rde_expert_workflow

# Build rule for target.
test_rde_expert_workflow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_rde_expert_workflow
.PHONY : test_rde_expert_workflow

# fast build rule for target.
test_rde_expert_workflow/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/build
.PHONY : test_rde_expert_workflow/fast

#=============================================================================
# Target rules for targets named test_complete_rde_system

# Build rule for target.
test_complete_rde_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_complete_rde_system
.PHONY : test_complete_rde_system

# fast build rule for target.
test_complete_rde_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/build
.PHONY : test_complete_rde_system/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mcp/json_rpc.o: src/mcp/json_rpc.cpp.o
.PHONY : src/mcp/json_rpc.o

# target to build an object file
src/mcp/json_rpc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/mcp/json_rpc.cpp.o
.PHONY : src/mcp/json_rpc.cpp.o

src/mcp/json_rpc.i: src/mcp/json_rpc.cpp.i
.PHONY : src/mcp/json_rpc.i

# target to preprocess a source file
src/mcp/json_rpc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/mcp/json_rpc.cpp.i
.PHONY : src/mcp/json_rpc.cpp.i

src/mcp/json_rpc.s: src/mcp/json_rpc.cpp.s
.PHONY : src/mcp/json_rpc.s

# target to generate assembly for a file
src/mcp/json_rpc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/mcp/json_rpc.cpp.s
.PHONY : src/mcp/json_rpc.cpp.s

src/mcp/server.o: src/mcp/server.cpp.o
.PHONY : src/mcp/server.o

# target to build an object file
src/mcp/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/mcp/server.cpp.o
.PHONY : src/mcp/server.cpp.o

src/mcp/server.i: src/mcp/server.cpp.i
.PHONY : src/mcp/server.i

# target to preprocess a source file
src/mcp/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/mcp/server.cpp.i
.PHONY : src/mcp/server.cpp.i

src/mcp/server.s: src/mcp/server.cpp.s
.PHONY : src/mcp/server.s

# target to generate assembly for a file
src/mcp/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/mcp/server.cpp.s
.PHONY : src/mcp/server.cpp.s

src/openfoam/case_manager.o: src/openfoam/case_manager.cpp.o
.PHONY : src/openfoam/case_manager.o

# target to build an object file
src/openfoam/case_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/case_manager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/src/openfoam/case_manager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/src/openfoam/case_manager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/openfoam/case_manager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/openfoam/case_manager.cpp.o
.PHONY : src/openfoam/case_manager.cpp.o

src/openfoam/case_manager.i: src/openfoam/case_manager.cpp.i
.PHONY : src/openfoam/case_manager.i

# target to preprocess a source file
src/openfoam/case_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/case_manager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/src/openfoam/case_manager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/src/openfoam/case_manager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/openfoam/case_manager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/openfoam/case_manager.cpp.i
.PHONY : src/openfoam/case_manager.cpp.i

src/openfoam/case_manager.s: src/openfoam/case_manager.cpp.s
.PHONY : src/openfoam/case_manager.s

# target to generate assembly for a file
src/openfoam/case_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/case_manager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/src/openfoam/case_manager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/src/openfoam/case_manager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/openfoam/case_manager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/openfoam/case_manager.cpp.s
.PHONY : src/openfoam/case_manager.cpp.s

src/openfoam/cellular_detonation_model.o: src/openfoam/cellular_detonation_model.cpp.o
.PHONY : src/openfoam/cellular_detonation_model.o

# target to build an object file
src/openfoam/cellular_detonation_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/cellular_detonation_model.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/src/openfoam/cellular_detonation_model.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/src/openfoam/cellular_detonation_model.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/openfoam/cellular_detonation_model.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/openfoam/cellular_detonation_model.cpp.o
.PHONY : src/openfoam/cellular_detonation_model.cpp.o

src/openfoam/cellular_detonation_model.i: src/openfoam/cellular_detonation_model.cpp.i
.PHONY : src/openfoam/cellular_detonation_model.i

# target to preprocess a source file
src/openfoam/cellular_detonation_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/cellular_detonation_model.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/src/openfoam/cellular_detonation_model.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/src/openfoam/cellular_detonation_model.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/openfoam/cellular_detonation_model.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/openfoam/cellular_detonation_model.cpp.i
.PHONY : src/openfoam/cellular_detonation_model.cpp.i

src/openfoam/cellular_detonation_model.s: src/openfoam/cellular_detonation_model.cpp.s
.PHONY : src/openfoam/cellular_detonation_model.s

# target to generate assembly for a file
src/openfoam/cellular_detonation_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/cellular_detonation_model.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/src/openfoam/cellular_detonation_model.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/src/openfoam/cellular_detonation_model.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/openfoam/cellular_detonation_model.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/openfoam/cellular_detonation_model.cpp.s
.PHONY : src/openfoam/cellular_detonation_model.cpp.s

src/openfoam/external_flow.o: src/openfoam/external_flow.cpp.o
.PHONY : src/openfoam/external_flow.o

# target to build an object file
src/openfoam/external_flow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/external_flow.cpp.o
.PHONY : src/openfoam/external_flow.cpp.o

src/openfoam/external_flow.i: src/openfoam/external_flow.cpp.i
.PHONY : src/openfoam/external_flow.i

# target to preprocess a source file
src/openfoam/external_flow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/external_flow.cpp.i
.PHONY : src/openfoam/external_flow.cpp.i

src/openfoam/external_flow.s: src/openfoam/external_flow.cpp.s
.PHONY : src/openfoam/external_flow.s

# target to generate assembly for a file
src/openfoam/external_flow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/external_flow.cpp.s
.PHONY : src/openfoam/external_flow.cpp.s

src/openfoam/heat_transfer.o: src/openfoam/heat_transfer.cpp.o
.PHONY : src/openfoam/heat_transfer.o

# target to build an object file
src/openfoam/heat_transfer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/heat_transfer.cpp.o
.PHONY : src/openfoam/heat_transfer.cpp.o

src/openfoam/heat_transfer.i: src/openfoam/heat_transfer.cpp.i
.PHONY : src/openfoam/heat_transfer.i

# target to preprocess a source file
src/openfoam/heat_transfer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/heat_transfer.cpp.i
.PHONY : src/openfoam/heat_transfer.cpp.i

src/openfoam/heat_transfer.s: src/openfoam/heat_transfer.cpp.s
.PHONY : src/openfoam/heat_transfer.s

# target to generate assembly for a file
src/openfoam/heat_transfer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/heat_transfer.cpp.s
.PHONY : src/openfoam/heat_transfer.cpp.s

src/openfoam/mesh_quality.o: src/openfoam/mesh_quality.cpp.o
.PHONY : src/openfoam/mesh_quality.o

# target to build an object file
src/openfoam/mesh_quality.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/mesh_quality.cpp.o
.PHONY : src/openfoam/mesh_quality.cpp.o

src/openfoam/mesh_quality.i: src/openfoam/mesh_quality.cpp.i
.PHONY : src/openfoam/mesh_quality.i

# target to preprocess a source file
src/openfoam/mesh_quality.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/mesh_quality.cpp.i
.PHONY : src/openfoam/mesh_quality.cpp.i

src/openfoam/mesh_quality.s: src/openfoam/mesh_quality.cpp.s
.PHONY : src/openfoam/mesh_quality.s

# target to generate assembly for a file
src/openfoam/mesh_quality.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/mesh_quality.cpp.s
.PHONY : src/openfoam/mesh_quality.cpp.s

src/openfoam/multiphase_flow.o: src/openfoam/multiphase_flow.cpp.o
.PHONY : src/openfoam/multiphase_flow.o

# target to build an object file
src/openfoam/multiphase_flow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/multiphase_flow.cpp.o
.PHONY : src/openfoam/multiphase_flow.cpp.o

src/openfoam/multiphase_flow.i: src/openfoam/multiphase_flow.cpp.i
.PHONY : src/openfoam/multiphase_flow.i

# target to preprocess a source file
src/openfoam/multiphase_flow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/multiphase_flow.cpp.i
.PHONY : src/openfoam/multiphase_flow.cpp.i

src/openfoam/multiphase_flow.s: src/openfoam/multiphase_flow.cpp.s
.PHONY : src/openfoam/multiphase_flow.s

# target to generate assembly for a file
src/openfoam/multiphase_flow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/multiphase_flow.cpp.s
.PHONY : src/openfoam/multiphase_flow.cpp.s

src/openfoam/pipe_flow.o: src/openfoam/pipe_flow.cpp.o
.PHONY : src/openfoam/pipe_flow.o

# target to build an object file
src/openfoam/pipe_flow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/pipe_flow.cpp.o
.PHONY : src/openfoam/pipe_flow.cpp.o

src/openfoam/pipe_flow.i: src/openfoam/pipe_flow.cpp.i
.PHONY : src/openfoam/pipe_flow.i

# target to preprocess a source file
src/openfoam/pipe_flow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/pipe_flow.cpp.i
.PHONY : src/openfoam/pipe_flow.cpp.i

src/openfoam/pipe_flow.s: src/openfoam/pipe_flow.cpp.s
.PHONY : src/openfoam/pipe_flow.s

# target to generate assembly for a file
src/openfoam/pipe_flow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/pipe_flow.cpp.s
.PHONY : src/openfoam/pipe_flow.cpp.s

src/openfoam/rde_expert_workflow.o: src/openfoam/rde_expert_workflow.cpp.o
.PHONY : src/openfoam/rde_expert_workflow.o

# target to build an object file
src/openfoam/rde_expert_workflow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/rde_expert_workflow.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/openfoam/rde_expert_workflow.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/openfoam/rde_expert_workflow.cpp.o
.PHONY : src/openfoam/rde_expert_workflow.cpp.o

src/openfoam/rde_expert_workflow.i: src/openfoam/rde_expert_workflow.cpp.i
.PHONY : src/openfoam/rde_expert_workflow.i

# target to preprocess a source file
src/openfoam/rde_expert_workflow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/rde_expert_workflow.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/openfoam/rde_expert_workflow.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/openfoam/rde_expert_workflow.cpp.i
.PHONY : src/openfoam/rde_expert_workflow.cpp.i

src/openfoam/rde_expert_workflow.s: src/openfoam/rde_expert_workflow.cpp.s
.PHONY : src/openfoam/rde_expert_workflow.s

# target to generate assembly for a file
src/openfoam/rde_expert_workflow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/rde_expert_workflow.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/openfoam/rde_expert_workflow.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/openfoam/rde_expert_workflow.cpp.s
.PHONY : src/openfoam/rde_expert_workflow.cpp.s

src/openfoam/rotating_detonation_engine.o: src/openfoam/rotating_detonation_engine.cpp.o
.PHONY : src/openfoam/rotating_detonation_engine.o

# target to build an object file
src/openfoam/rotating_detonation_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/rotating_detonation_engine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/src/openfoam/rotating_detonation_engine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/src/openfoam/rotating_detonation_engine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/openfoam/rotating_detonation_engine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/openfoam/rotating_detonation_engine.cpp.o
.PHONY : src/openfoam/rotating_detonation_engine.cpp.o

src/openfoam/rotating_detonation_engine.i: src/openfoam/rotating_detonation_engine.cpp.i
.PHONY : src/openfoam/rotating_detonation_engine.i

# target to preprocess a source file
src/openfoam/rotating_detonation_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/rotating_detonation_engine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/src/openfoam/rotating_detonation_engine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/src/openfoam/rotating_detonation_engine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/openfoam/rotating_detonation_engine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/openfoam/rotating_detonation_engine.cpp.i
.PHONY : src/openfoam/rotating_detonation_engine.cpp.i

src/openfoam/rotating_detonation_engine.s: src/openfoam/rotating_detonation_engine.cpp.s
.PHONY : src/openfoam/rotating_detonation_engine.s

# target to generate assembly for a file
src/openfoam/rotating_detonation_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/rotating_detonation_engine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/src/openfoam/rotating_detonation_engine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/src/openfoam/rotating_detonation_engine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/openfoam/rotating_detonation_engine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/openfoam/rotating_detonation_engine.cpp.s
.PHONY : src/openfoam/rotating_detonation_engine.cpp.s

src/openfoam/snappy_templates.o: src/openfoam/snappy_templates.cpp.o
.PHONY : src/openfoam/snappy_templates.o

# target to build an object file
src/openfoam/snappy_templates.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/snappy_templates.cpp.o
.PHONY : src/openfoam/snappy_templates.cpp.o

src/openfoam/snappy_templates.i: src/openfoam/snappy_templates.cpp.i
.PHONY : src/openfoam/snappy_templates.i

# target to preprocess a source file
src/openfoam/snappy_templates.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/snappy_templates.cpp.i
.PHONY : src/openfoam/snappy_templates.cpp.i

src/openfoam/snappy_templates.s: src/openfoam/snappy_templates.cpp.s
.PHONY : src/openfoam/snappy_templates.s

# target to generate assembly for a file
src/openfoam/snappy_templates.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/snappy_templates.cpp.s
.PHONY : src/openfoam/snappy_templates.cpp.s

src/openfoam/stl_analyzer.o: src/openfoam/stl_analyzer.cpp.o
.PHONY : src/openfoam/stl_analyzer.o

# target to build an object file
src/openfoam/stl_analyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/stl_analyzer.cpp.o
.PHONY : src/openfoam/stl_analyzer.cpp.o

src/openfoam/stl_analyzer.i: src/openfoam/stl_analyzer.cpp.i
.PHONY : src/openfoam/stl_analyzer.i

# target to preprocess a source file
src/openfoam/stl_analyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/stl_analyzer.cpp.i
.PHONY : src/openfoam/stl_analyzer.cpp.i

src/openfoam/stl_analyzer.s: src/openfoam/stl_analyzer.cpp.s
.PHONY : src/openfoam/stl_analyzer.s

# target to generate assembly for a file
src/openfoam/stl_analyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/openfoam/stl_analyzer.cpp.s
.PHONY : src/openfoam/stl_analyzer.cpp.s

src/physics/cantera_wrapper.o: src/physics/cantera_wrapper.cpp.o
.PHONY : src/physics/cantera_wrapper.o

# target to build an object file
src/physics/cantera_wrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/physics/cantera_wrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cantera_wrapper.dir/build.make CMakeFiles/test_cantera_wrapper.dir/src/physics/cantera_wrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_comprehensive_validation.dir/build.make CMakeFiles/test_comprehensive_validation.dir/src/physics/cantera_wrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/src/physics/cantera_wrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/src/physics/cantera_wrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/physics/cantera_wrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/physics/cantera_wrapper.cpp.o
.PHONY : src/physics/cantera_wrapper.cpp.o

src/physics/cantera_wrapper.i: src/physics/cantera_wrapper.cpp.i
.PHONY : src/physics/cantera_wrapper.i

# target to preprocess a source file
src/physics/cantera_wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/physics/cantera_wrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cantera_wrapper.dir/build.make CMakeFiles/test_cantera_wrapper.dir/src/physics/cantera_wrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_comprehensive_validation.dir/build.make CMakeFiles/test_comprehensive_validation.dir/src/physics/cantera_wrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/src/physics/cantera_wrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/src/physics/cantera_wrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/physics/cantera_wrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/physics/cantera_wrapper.cpp.i
.PHONY : src/physics/cantera_wrapper.cpp.i

src/physics/cantera_wrapper.s: src/physics/cantera_wrapper.cpp.s
.PHONY : src/physics/cantera_wrapper.s

# target to generate assembly for a file
src/physics/cantera_wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/physics/cantera_wrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cantera_wrapper.dir/build.make CMakeFiles/test_cantera_wrapper.dir/src/physics/cantera_wrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_comprehensive_validation.dir/build.make CMakeFiles/test_comprehensive_validation.dir/src/physics/cantera_wrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/src/physics/cantera_wrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/src/physics/cantera_wrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/src/physics/cantera_wrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/src/physics/cantera_wrapper.cpp.s
.PHONY : src/physics/cantera_wrapper.cpp.s

src/physics/test_cantera_wrapper.o: src/physics/test_cantera_wrapper.cpp.o
.PHONY : src/physics/test_cantera_wrapper.o

# target to build an object file
src/physics/test_cantera_wrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cantera_wrapper.dir/build.make CMakeFiles/test_cantera_wrapper.dir/src/physics/test_cantera_wrapper.cpp.o
.PHONY : src/physics/test_cantera_wrapper.cpp.o

src/physics/test_cantera_wrapper.i: src/physics/test_cantera_wrapper.cpp.i
.PHONY : src/physics/test_cantera_wrapper.i

# target to preprocess a source file
src/physics/test_cantera_wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cantera_wrapper.dir/build.make CMakeFiles/test_cantera_wrapper.dir/src/physics/test_cantera_wrapper.cpp.i
.PHONY : src/physics/test_cantera_wrapper.cpp.i

src/physics/test_cantera_wrapper.s: src/physics/test_cantera_wrapper.cpp.s
.PHONY : src/physics/test_cantera_wrapper.s

# target to generate assembly for a file
src/physics/test_cantera_wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cantera_wrapper.dir/build.make CMakeFiles/test_cantera_wrapper.dir/src/physics/test_cantera_wrapper.cpp.s
.PHONY : src/physics/test_cantera_wrapper.cpp.s

src/tools/cfd_assistant_registration.o: src/tools/cfd_assistant_registration.cpp.o
.PHONY : src/tools/cfd_assistant_registration.o

# target to build an object file
src/tools/cfd_assistant_registration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/cfd_assistant_registration.cpp.o
.PHONY : src/tools/cfd_assistant_registration.cpp.o

src/tools/cfd_assistant_registration.i: src/tools/cfd_assistant_registration.cpp.i
.PHONY : src/tools/cfd_assistant_registration.i

# target to preprocess a source file
src/tools/cfd_assistant_registration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/cfd_assistant_registration.cpp.i
.PHONY : src/tools/cfd_assistant_registration.cpp.i

src/tools/cfd_assistant_registration.s: src/tools/cfd_assistant_registration.cpp.s
.PHONY : src/tools/cfd_assistant_registration.s

# target to generate assembly for a file
src/tools/cfd_assistant_registration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/cfd_assistant_registration.cpp.s
.PHONY : src/tools/cfd_assistant_registration.cpp.s

src/tools/cfd_assistant_tool.o: src/tools/cfd_assistant_tool.cpp.o
.PHONY : src/tools/cfd_assistant_tool.o

# target to build an object file
src/tools/cfd_assistant_tool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/cfd_assistant_tool.cpp.o
.PHONY : src/tools/cfd_assistant_tool.cpp.o

src/tools/cfd_assistant_tool.i: src/tools/cfd_assistant_tool.cpp.i
.PHONY : src/tools/cfd_assistant_tool.i

# target to preprocess a source file
src/tools/cfd_assistant_tool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/cfd_assistant_tool.cpp.i
.PHONY : src/tools/cfd_assistant_tool.cpp.i

src/tools/cfd_assistant_tool.s: src/tools/cfd_assistant_tool.cpp.s
.PHONY : src/tools/cfd_assistant_tool.s

# target to generate assembly for a file
src/tools/cfd_assistant_tool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/cfd_assistant_tool.cpp.s
.PHONY : src/tools/cfd_assistant_tool.cpp.s

src/tools/context_engine.o: src/tools/context_engine.cpp.o
.PHONY : src/tools/context_engine.o

# target to build an object file
src/tools/context_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/context_engine.cpp.o
.PHONY : src/tools/context_engine.cpp.o

src/tools/context_engine.i: src/tools/context_engine.cpp.i
.PHONY : src/tools/context_engine.i

# target to preprocess a source file
src/tools/context_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/context_engine.cpp.i
.PHONY : src/tools/context_engine.cpp.i

src/tools/context_engine.s: src/tools/context_engine.cpp.s
.PHONY : src/tools/context_engine.s

# target to generate assembly for a file
src/tools/context_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/context_engine.cpp.s
.PHONY : src/tools/context_engine.cpp.s

src/tools/external_flow_tool.o: src/tools/external_flow_tool.cpp.o
.PHONY : src/tools/external_flow_tool.o

# target to build an object file
src/tools/external_flow_tool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/external_flow_tool.cpp.o
.PHONY : src/tools/external_flow_tool.cpp.o

src/tools/external_flow_tool.i: src/tools/external_flow_tool.cpp.i
.PHONY : src/tools/external_flow_tool.i

# target to preprocess a source file
src/tools/external_flow_tool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/external_flow_tool.cpp.i
.PHONY : src/tools/external_flow_tool.cpp.i

src/tools/external_flow_tool.s: src/tools/external_flow_tool.cpp.s
.PHONY : src/tools/external_flow_tool.s

# target to generate assembly for a file
src/tools/external_flow_tool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/external_flow_tool.cpp.s
.PHONY : src/tools/external_flow_tool.cpp.s

src/tools/heat_transfer_tool.o: src/tools/heat_transfer_tool.cpp.o
.PHONY : src/tools/heat_transfer_tool.o

# target to build an object file
src/tools/heat_transfer_tool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/heat_transfer_tool.cpp.o
.PHONY : src/tools/heat_transfer_tool.cpp.o

src/tools/heat_transfer_tool.i: src/tools/heat_transfer_tool.cpp.i
.PHONY : src/tools/heat_transfer_tool.i

# target to preprocess a source file
src/tools/heat_transfer_tool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/heat_transfer_tool.cpp.i
.PHONY : src/tools/heat_transfer_tool.cpp.i

src/tools/heat_transfer_tool.s: src/tools/heat_transfer_tool.cpp.s
.PHONY : src/tools/heat_transfer_tool.s

# target to generate assembly for a file
src/tools/heat_transfer_tool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/heat_transfer_tool.cpp.s
.PHONY : src/tools/heat_transfer_tool.cpp.s

src/tools/multiphase_flow_tool.o: src/tools/multiphase_flow_tool.cpp.o
.PHONY : src/tools/multiphase_flow_tool.o

# target to build an object file
src/tools/multiphase_flow_tool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/multiphase_flow_tool.cpp.o
.PHONY : src/tools/multiphase_flow_tool.cpp.o

src/tools/multiphase_flow_tool.i: src/tools/multiphase_flow_tool.cpp.i
.PHONY : src/tools/multiphase_flow_tool.i

# target to preprocess a source file
src/tools/multiphase_flow_tool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/multiphase_flow_tool.cpp.i
.PHONY : src/tools/multiphase_flow_tool.cpp.i

src/tools/multiphase_flow_tool.s: src/tools/multiphase_flow_tool.cpp.s
.PHONY : src/tools/multiphase_flow_tool.s

# target to generate assembly for a file
src/tools/multiphase_flow_tool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/multiphase_flow_tool.cpp.s
.PHONY : src/tools/multiphase_flow_tool.cpp.s

src/tools/pipe_flow_tool.o: src/tools/pipe_flow_tool.cpp.o
.PHONY : src/tools/pipe_flow_tool.o

# target to build an object file
src/tools/pipe_flow_tool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/pipe_flow_tool.cpp.o
.PHONY : src/tools/pipe_flow_tool.cpp.o

src/tools/pipe_flow_tool.i: src/tools/pipe_flow_tool.cpp.i
.PHONY : src/tools/pipe_flow_tool.i

# target to preprocess a source file
src/tools/pipe_flow_tool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/pipe_flow_tool.cpp.i
.PHONY : src/tools/pipe_flow_tool.cpp.i

src/tools/pipe_flow_tool.s: src/tools/pipe_flow_tool.cpp.s
.PHONY : src/tools/pipe_flow_tool.s

# target to generate assembly for a file
src/tools/pipe_flow_tool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/pipe_flow_tool.cpp.s
.PHONY : src/tools/pipe_flow_tool.cpp.s

src/tools/rde_analysis_tool.o: src/tools/rde_analysis_tool.cpp.o
.PHONY : src/tools/rde_analysis_tool.o

# target to build an object file
src/tools/rde_analysis_tool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/rde_analysis_tool.cpp.o
.PHONY : src/tools/rde_analysis_tool.cpp.o

src/tools/rde_analysis_tool.i: src/tools/rde_analysis_tool.cpp.i
.PHONY : src/tools/rde_analysis_tool.i

# target to preprocess a source file
src/tools/rde_analysis_tool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/rde_analysis_tool.cpp.i
.PHONY : src/tools/rde_analysis_tool.cpp.i

src/tools/rde_analysis_tool.s: src/tools/rde_analysis_tool.cpp.s
.PHONY : src/tools/rde_analysis_tool.s

# target to generate assembly for a file
src/tools/rde_analysis_tool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/rde_analysis_tool.cpp.s
.PHONY : src/tools/rde_analysis_tool.cpp.s

src/tools/snappy_mesh_tool.o: src/tools/snappy_mesh_tool.cpp.o
.PHONY : src/tools/snappy_mesh_tool.o

# target to build an object file
src/tools/snappy_mesh_tool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/snappy_mesh_tool.cpp.o
.PHONY : src/tools/snappy_mesh_tool.cpp.o

src/tools/snappy_mesh_tool.i: src/tools/snappy_mesh_tool.cpp.i
.PHONY : src/tools/snappy_mesh_tool.i

# target to preprocess a source file
src/tools/snappy_mesh_tool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/snappy_mesh_tool.cpp.i
.PHONY : src/tools/snappy_mesh_tool.cpp.i

src/tools/snappy_mesh_tool.s: src/tools/snappy_mesh_tool.cpp.s
.PHONY : src/tools/snappy_mesh_tool.s

# target to generate assembly for a file
src/tools/snappy_mesh_tool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/tools/snappy_mesh_tool.cpp.s
.PHONY : src/tools/snappy_mesh_tool.cpp.s

src/utils/logging.o: src/utils/logging.cpp.o
.PHONY : src/utils/logging.o

# target to build an object file
src/utils/logging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/utils/logging.cpp.o
.PHONY : src/utils/logging.cpp.o

src/utils/logging.i: src/utils/logging.cpp.i
.PHONY : src/utils/logging.i

# target to preprocess a source file
src/utils/logging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/utils/logging.cpp.i
.PHONY : src/utils/logging.cpp.i

src/utils/logging.s: src/utils/logging.cpp.s
.PHONY : src/utils/logging.s

# target to generate assembly for a file
src/utils/logging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/utils/logging.cpp.s
.PHONY : src/utils/logging.cpp.s

src/utils/terminal_manager.o: src/utils/terminal_manager.cpp.o
.PHONY : src/utils/terminal_manager.o

# target to build an object file
src/utils/terminal_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/utils/terminal_manager.cpp.o
.PHONY : src/utils/terminal_manager.cpp.o

src/utils/terminal_manager.i: src/utils/terminal_manager.cpp.i
.PHONY : src/utils/terminal_manager.i

# target to preprocess a source file
src/utils/terminal_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/utils/terminal_manager.cpp.i
.PHONY : src/utils/terminal_manager.cpp.i

src/utils/terminal_manager.s: src/utils/terminal_manager.cpp.s
.PHONY : src/utils/terminal_manager.s

# target to generate assembly for a file
src/utils/terminal_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/openfoam-mcp-server.dir/build.make CMakeFiles/openfoam-mcp-server.dir/src/utils/terminal_manager.cpp.s
.PHONY : src/utils/terminal_manager.cpp.s

test_cellular_detonation_model.o: test_cellular_detonation_model.cpp.o
.PHONY : test_cellular_detonation_model.o

# target to build an object file
test_cellular_detonation_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/test_cellular_detonation_model.cpp.o
.PHONY : test_cellular_detonation_model.cpp.o

test_cellular_detonation_model.i: test_cellular_detonation_model.cpp.i
.PHONY : test_cellular_detonation_model.i

# target to preprocess a source file
test_cellular_detonation_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/test_cellular_detonation_model.cpp.i
.PHONY : test_cellular_detonation_model.cpp.i

test_cellular_detonation_model.s: test_cellular_detonation_model.cpp.s
.PHONY : test_cellular_detonation_model.s

# target to generate assembly for a file
test_cellular_detonation_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cellular_detonation_model.dir/build.make CMakeFiles/test_cellular_detonation_model.dir/test_cellular_detonation_model.cpp.s
.PHONY : test_cellular_detonation_model.cpp.s

test_complete_rde_system.o: test_complete_rde_system.cpp.o
.PHONY : test_complete_rde_system.o

# target to build an object file
test_complete_rde_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/test_complete_rde_system.cpp.o
.PHONY : test_complete_rde_system.cpp.o

test_complete_rde_system.i: test_complete_rde_system.cpp.i
.PHONY : test_complete_rde_system.i

# target to preprocess a source file
test_complete_rde_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/test_complete_rde_system.cpp.i
.PHONY : test_complete_rde_system.cpp.i

test_complete_rde_system.s: test_complete_rde_system.cpp.s
.PHONY : test_complete_rde_system.s

# target to generate assembly for a file
test_complete_rde_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_complete_rde_system.dir/build.make CMakeFiles/test_complete_rde_system.dir/test_complete_rde_system.cpp.s
.PHONY : test_complete_rde_system.cpp.s

test_comprehensive_validation.o: test_comprehensive_validation.cpp.o
.PHONY : test_comprehensive_validation.o

# target to build an object file
test_comprehensive_validation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_comprehensive_validation.dir/build.make CMakeFiles/test_comprehensive_validation.dir/test_comprehensive_validation.cpp.o
.PHONY : test_comprehensive_validation.cpp.o

test_comprehensive_validation.i: test_comprehensive_validation.cpp.i
.PHONY : test_comprehensive_validation.i

# target to preprocess a source file
test_comprehensive_validation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_comprehensive_validation.dir/build.make CMakeFiles/test_comprehensive_validation.dir/test_comprehensive_validation.cpp.i
.PHONY : test_comprehensive_validation.cpp.i

test_comprehensive_validation.s: test_comprehensive_validation.cpp.s
.PHONY : test_comprehensive_validation.s

# target to generate assembly for a file
test_comprehensive_validation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_comprehensive_validation.dir/build.make CMakeFiles/test_comprehensive_validation.dir/test_comprehensive_validation.cpp.s
.PHONY : test_comprehensive_validation.cpp.s

test_rde_expert_workflow.o: test_rde_expert_workflow.cpp.o
.PHONY : test_rde_expert_workflow.o

# target to build an object file
test_rde_expert_workflow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/test_rde_expert_workflow.cpp.o
.PHONY : test_rde_expert_workflow.cpp.o

test_rde_expert_workflow.i: test_rde_expert_workflow.cpp.i
.PHONY : test_rde_expert_workflow.i

# target to preprocess a source file
test_rde_expert_workflow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/test_rde_expert_workflow.cpp.i
.PHONY : test_rde_expert_workflow.cpp.i

test_rde_expert_workflow.s: test_rde_expert_workflow.cpp.s
.PHONY : test_rde_expert_workflow.s

# target to generate assembly for a file
test_rde_expert_workflow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_expert_workflow.dir/build.make CMakeFiles/test_rde_expert_workflow.dir/test_rde_expert_workflow.cpp.s
.PHONY : test_rde_expert_workflow.cpp.s

test_rde_integration.o: test_rde_integration.cpp.o
.PHONY : test_rde_integration.o

# target to build an object file
test_rde_integration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/test_rde_integration.cpp.o
.PHONY : test_rde_integration.cpp.o

test_rde_integration.i: test_rde_integration.cpp.i
.PHONY : test_rde_integration.i

# target to preprocess a source file
test_rde_integration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/test_rde_integration.cpp.i
.PHONY : test_rde_integration.cpp.i

test_rde_integration.s: test_rde_integration.cpp.s
.PHONY : test_rde_integration.s

# target to generate assembly for a file
test_rde_integration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rde_integration.dir/build.make CMakeFiles/test_rde_integration.dir/test_rde_integration.cpp.s
.PHONY : test_rde_integration.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... openfoam-mcp-server"
	@echo "... test_cantera_wrapper"
	@echo "... test_cellular_detonation_model"
	@echo "... test_complete_rde_system"
	@echo "... test_comprehensive_validation"
	@echo "... test_rde_expert_workflow"
	@echo "... test_rde_integration"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mcp/json_rpc.o"
	@echo "... src/mcp/json_rpc.i"
	@echo "... src/mcp/json_rpc.s"
	@echo "... src/mcp/server.o"
	@echo "... src/mcp/server.i"
	@echo "... src/mcp/server.s"
	@echo "... src/openfoam/case_manager.o"
	@echo "... src/openfoam/case_manager.i"
	@echo "... src/openfoam/case_manager.s"
	@echo "... src/openfoam/cellular_detonation_model.o"
	@echo "... src/openfoam/cellular_detonation_model.i"
	@echo "... src/openfoam/cellular_detonation_model.s"
	@echo "... src/openfoam/external_flow.o"
	@echo "... src/openfoam/external_flow.i"
	@echo "... src/openfoam/external_flow.s"
	@echo "... src/openfoam/heat_transfer.o"
	@echo "... src/openfoam/heat_transfer.i"
	@echo "... src/openfoam/heat_transfer.s"
	@echo "... src/openfoam/mesh_quality.o"
	@echo "... src/openfoam/mesh_quality.i"
	@echo "... src/openfoam/mesh_quality.s"
	@echo "... src/openfoam/multiphase_flow.o"
	@echo "... src/openfoam/multiphase_flow.i"
	@echo "... src/openfoam/multiphase_flow.s"
	@echo "... src/openfoam/pipe_flow.o"
	@echo "... src/openfoam/pipe_flow.i"
	@echo "... src/openfoam/pipe_flow.s"
	@echo "... src/openfoam/rde_expert_workflow.o"
	@echo "... src/openfoam/rde_expert_workflow.i"
	@echo "... src/openfoam/rde_expert_workflow.s"
	@echo "... src/openfoam/rotating_detonation_engine.o"
	@echo "... src/openfoam/rotating_detonation_engine.i"
	@echo "... src/openfoam/rotating_detonation_engine.s"
	@echo "... src/openfoam/snappy_templates.o"
	@echo "... src/openfoam/snappy_templates.i"
	@echo "... src/openfoam/snappy_templates.s"
	@echo "... src/openfoam/stl_analyzer.o"
	@echo "... src/openfoam/stl_analyzer.i"
	@echo "... src/openfoam/stl_analyzer.s"
	@echo "... src/physics/cantera_wrapper.o"
	@echo "... src/physics/cantera_wrapper.i"
	@echo "... src/physics/cantera_wrapper.s"
	@echo "... src/physics/test_cantera_wrapper.o"
	@echo "... src/physics/test_cantera_wrapper.i"
	@echo "... src/physics/test_cantera_wrapper.s"
	@echo "... src/tools/cfd_assistant_registration.o"
	@echo "... src/tools/cfd_assistant_registration.i"
	@echo "... src/tools/cfd_assistant_registration.s"
	@echo "... src/tools/cfd_assistant_tool.o"
	@echo "... src/tools/cfd_assistant_tool.i"
	@echo "... src/tools/cfd_assistant_tool.s"
	@echo "... src/tools/context_engine.o"
	@echo "... src/tools/context_engine.i"
	@echo "... src/tools/context_engine.s"
	@echo "... src/tools/external_flow_tool.o"
	@echo "... src/tools/external_flow_tool.i"
	@echo "... src/tools/external_flow_tool.s"
	@echo "... src/tools/heat_transfer_tool.o"
	@echo "... src/tools/heat_transfer_tool.i"
	@echo "... src/tools/heat_transfer_tool.s"
	@echo "... src/tools/multiphase_flow_tool.o"
	@echo "... src/tools/multiphase_flow_tool.i"
	@echo "... src/tools/multiphase_flow_tool.s"
	@echo "... src/tools/pipe_flow_tool.o"
	@echo "... src/tools/pipe_flow_tool.i"
	@echo "... src/tools/pipe_flow_tool.s"
	@echo "... src/tools/rde_analysis_tool.o"
	@echo "... src/tools/rde_analysis_tool.i"
	@echo "... src/tools/rde_analysis_tool.s"
	@echo "... src/tools/snappy_mesh_tool.o"
	@echo "... src/tools/snappy_mesh_tool.i"
	@echo "... src/tools/snappy_mesh_tool.s"
	@echo "... src/utils/logging.o"
	@echo "... src/utils/logging.i"
	@echo "... src/utils/logging.s"
	@echo "... src/utils/terminal_manager.o"
	@echo "... src/utils/terminal_manager.i"
	@echo "... src/utils/terminal_manager.s"
	@echo "... test_cellular_detonation_model.o"
	@echo "... test_cellular_detonation_model.i"
	@echo "... test_cellular_detonation_model.s"
	@echo "... test_complete_rde_system.o"
	@echo "... test_complete_rde_system.i"
	@echo "... test_complete_rde_system.s"
	@echo "... test_comprehensive_validation.o"
	@echo "... test_comprehensive_validation.i"
	@echo "... test_comprehensive_validation.s"
	@echo "... test_rde_expert_workflow.o"
	@echo "... test_rde_expert_workflow.i"
	@echo "... test_rde_expert_workflow.s"
	@echo "... test_rde_integration.o"
	@echo "... test_rde_integration.i"
	@echo "... test_rde_integration.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

